# readiness check: docker exec book-pg-test pg_isready -U postgres

services:
  db:
    image: postgres:16
    restart: no
    container_name: book-pg-test
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    command: >
      postgres
      -c fsync=off
      -c synchronous_commit=off
      -c full_page_writes=off
    tmpfs:
      - /var/lib/postgresql/data
