name: CI

on:
  push:
    branches:
      - main
      - feature/*
      - release/v*
      - testing/**

  pull_request:
    branches:
      - main

jobs:
  biome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pnpm setup
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Biome
        run: pnpm biome:ci

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pnpm setup
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Prisma init
        run: pnpm prisma:init:test

      - name: Type check
        run: pnpm check

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pnpm setup
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Prisma init
        run: pnpm prisma:init:test

      - name: Run unit tests
        run: pnpm test:band

  build:
    runs-on: ubuntu-latest
    needs:
      - biome
      - typecheck
      - test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pnpm setup
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Prisma init
        run: pnpm prisma:init:test

      - name: Build project
        run: pnpm build